# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 08:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctorprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialisation', models.CharField(choices=[('General Practitioner', 'General Practitioner'), ('Dermatologist', 'Dermatologist'), ('Urologist', 'Urologist')], default='General Practitioner', help_text='Your specialisation', max_length=50)),
                ('useri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('is_doctor', 'is_doctor'),),
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('quantity', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentf', models.CharField(default='Shrey', max_length=500)),
                ('studentl', models.CharField(default='Tanna', max_length=500)),
                ('condition', models.CharField(default='Enter condition here', help_text='Name of disease', max_length=50)),
                ('problem_discription', models.CharField(default='Problem discription', help_text='Discription of problem', max_length=5000)),
                ('other_advise', models.CharField(default='Enter advise', max_length=5000)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('medicines', models.ManyToManyField(help_text='Select medicines', to='medicare.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Studentprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('hostel', models.CharField(choices=[('ASN Bose', 'ASN Bose'), ('Visvesvaraya', 'Visvesvaraya'), ('Ramanujan', 'Ramanujan')], default='Ramanujan', help_text='Present hostel', max_length=50)),
                ('department', models.CharField(choices=[('Computer Science and Engineering', 'Computer Science and Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Maths and Computing', 'Maths and Computing')], default='Computer Science and Engineering', help_text='Department', max_length=50)),
                ('blood_group', models.CharField(choices=[('O+', 'O+'), ('B+', 'B+'), ('A', 'A')], default='B+', help_text='Blood group', max_length=50)),
                ('pic', models.FileField(null=True, upload_to='')),
                ('useri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('is_student', 'is_student'),),
            },
        ),
    ]
